# Generated by Django 4.2.9 on 2024-02-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertournamentgroup",
            name="entered_at",
        ),
    ]
