# Generated by Django 4.2.9 on 2024-01-31 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentgroup_usertournamentgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.tournament'),
        ),
    ]
