# Generated by Django 4.2.9 on 2024-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournamentgroup_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertournamentgroup',
            name='claimed_reward',
            field=models.BooleanField(default=False),
        ),
    ]
