runtime: python39

entrypoint: gunicorn -b :$PORT GoodBlast.wsgi
env_variables:
  APPENGINE_URL: https://good-blast-413306.uc.r.appspot.com
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto