version: '3.9'
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    volumes:
     - static_volume:/home/app/web/staticfiles
     - media_volume:/home/app/web/mediafiles
    ports:
    - "8000:8000"
    restart: "on-failure"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
     - ~/apps/postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=GoodBlast

volumes:
  postgres_data:
  static_volume:
  media_volume: