# Generated by Django 5.0.1 on 2024-01-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_country_user_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_code',
            new_name='country',
        ),
    ]
