# Generated by Django 5.0.1 on 2024-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_country_code_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
